# Generated by Django 4.2 on 2023-05-06 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='location',
        ),
        migrations.RemoveField(
            model_name='store',
            name='product',
        ),
        migrations.RemoveField(
            model_name='store',
            name='retailerID',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='watchlistProduct',
            new_name='products',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='itemCount',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='userID',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='name',
            field=models.CharField(default='New Watchlist', max_length=100),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Retailer',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
