# Generated by Django 4.2 on 2023-05-06 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_store_location_remove_store_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='name',
            new_name='title',
        ),
    ]
