# Generated by Django 4.2 on 2023-05-14 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_product_category_alter_product_description_and_more'),
        ('core', '0008_profile_birthdate'),
    ]

    operations = [
    ]
