# Generated by Django 4.2 on 2023-05-19 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_historicalprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
    ]
