# Generated by Django 4.2 on 2023-05-21 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_historicalprice_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalprice',
            options={'ordering': ['-date']},
        ),
    ]
